"""empty message

Revision ID: 0c803fe20d4e
Revises: 94697bbdc2f1
Create Date: 2025-02-24 00:18:10.143554

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c803fe20d4e'
down_revision: Union[str, None] = '94697bbdc2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('promotions', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'position')
    op.drop_column('products', 'position')
    # ### end Alembic commands ###
