"""empty message

Revision ID: 20afdaa4a9e1
Revises: 331bad906afd
Create Date: 2025-02-16 16:52:59.360303

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20afdaa4a9e1'
down_revision: Union[str, None] = '331bad906afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   # op.drop_table('discounts')
  #  op.drop_table('categories')
    op.add_column('conditions', sa.Column('title_uz', sa.String(), nullable=True))
    op.add_column('news', sa.Column('title_uz', sa.String(), nullable=True))
    op.add_column('news', sa.Column('content_uz', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('title_uz', sa.String(), nullable=True))
    op.add_column('products', sa.Column('description_uz', sa.String(), nullable=True))
    op.add_column('products', sa.Column('new_price', sa.Float(), nullable=True))
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_discount_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'discount_id')
    op.drop_column('products', 'category_id')
    op.add_column('promotions', sa.Column('title_uz', sa.String(), nullable=True))
    op.add_column('promotions', sa.Column('content_uz', sa.Text(), nullable=True))
    op.add_column('shops', sa.Column('title_uz', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('address_uz', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('landmark_uz', sa.String(), nullable=True))
    op.add_column('socials', sa.Column('title_uz', sa.String(), nullable=True))
    op.add_column('vacancies', sa.Column('title_uz', sa.String(), nullable=True))
    op.add_column('vacancies', sa.Column('description_uz', sa.String(), nullable=True))
    op.add_column('vacancies', sa.Column('address_uz', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'address_uz')
    op.drop_column('vacancies', 'description_uz')
    op.drop_column('vacancies', 'title_uz')
    op.drop_column('socials', 'title_uz')
    op.drop_column('shops', 'landmark_uz')
    op.drop_column('shops', 'address_uz')
    op.drop_column('shops', 'title_uz')
    op.drop_column('promotions', 'content_uz')
    op.drop_column('promotions', 'title_uz')
    op.add_column('products', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('discount_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_discount_id_fkey', 'products', 'discounts', ['discount_id'], ['id'])
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'new_price')
    op.drop_column('products', 'description_uz')
    op.drop_column('products', 'title_uz')
    op.drop_column('news', 'content_uz')
    op.drop_column('news', 'title_uz')
    op.drop_column('conditions', 'title_uz')
    op.create_table('categories',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='categories_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    op.create_table('discounts',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('discount_type', postgresql.ENUM('percent', 'fixed', name='discounttypeenum'), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='discounts_pkey')
    )
    # ### end Alembic commands ###
