"""empty message

Revision ID: 331bad906afd
Revises: 56296ba9c3a4
Create Date: 2025-02-07 11:21:36.950677

"""

from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "331bad906afd"
down_revision: Union[str, None] = "56296ba9c3a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("promotions", sa.Column("poster", sa.String(), nullable=True))
    op.add_column("promotions", sa.Column("poster_url", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promotions", "poster_url")
    op.drop_column("promotions", "poster")
    # ### end Alembic commands ###
