"""empty message

Revision ID: 94697bbdc2f1
Revises: 20afdaa4a9e1
Create Date: 2025-02-19 20:46:52.757960

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94697bbdc2f1'
down_revision: Union[str, None] = '20afdaa4a9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discounts')
    op.drop_table('categories')
    op.alter_column('conditions', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('news', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('news', 'content_uz',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('products', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'description_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('promotions', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('promotions', 'content_uz',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('shops', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shops', 'address_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shops', 'landmark_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('socials', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancies', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancies', 'description_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancies', 'address_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'address_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancies', 'description_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancies', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('socials', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shops', 'landmark_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shops', 'address_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shops', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('promotions', 'content_uz',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('promotions', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'description_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('news', 'content_uz',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('news', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conditions', 'title_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('categories',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='categories_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    op.create_table('discounts',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('discount_type', postgresql.ENUM('percent', 'fixed', name='discounttypeenum'), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='discounts_pkey')
    )
    # ### end Alembic commands ###
